//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RURWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweet
    {
        public int id { get; set; }
        public string tweet_id { get; set; }
        public string text { get; set; }
        public string quoted_id { get; set; }
        public string retweet_id { get; set; }
        public string username { get; set; }
        public string screen_name { get; set; }
        public string created_at { get; set; }
        public string user_location { get; set; }
        public string place { get; set; }
        public Nullable<byte> verified { get; set; }
    }
}
